### ISSUE TITLE
Add support for Sonar

### ISSUE THREAD

**Issue by dimasmith** [dimasmith/ci-server-setup#4]
# Deploy Sonar with MySQL

### Tasks
- [x] Deploy sonar
- [x] Deploy mysql
- [x] Cover sonar with gateway
- [x] Document installation and customization

### Checks
- [x] Sonar port can be changed
- [x] Sonar domain can be changed
- [x] Sonar version can be changed

**Comment by dimasmith** [comment]
### Tasks
- [ ] Deploy sonar
- [ ] Deploy mysql
- [ ] Cover sonar with gateway
- [ ] Document installation and customization

### Checks
- [ ] Sonar port can be changed
- [ ] Sonar domain can be changed
- [ ] Sonar version can be changed
